export const LOAD_PORTFOLIO = "LOAD_PORTFOLIO";
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO";
export const UPDATE_PORTFOLIO_LINK = "UPDATE_PORTFOLIO_LINK";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const LOGOUT = "LOGOUT";
export const LOAD_ACTIVITIES = "LOAD_ACTIVITIES";
export const LOAD_ACTIVITY_ID = "LOAD_ACTIVITY_ID";