export const SET_EVENTS = "SET_EVENTS";
export const SET_EVENT = "SET_EVENT";
export const GIVE_BADGE_SELECT_STUDENT = "GIVE_BADGE_SELECT_STUDENT";
export const GIVE_BADGE_SELECT_BADGE = "GIVE_BADGE_SELECT_BADGE";
export const GIVE_BADGE_CONFIRM_BADGE = "GIVE_BADGE_CONFIRM_BADGE";
export const GIVE_BADGE_SUCCESS = "GIVE_BADGE_SUCCESS";
export const GIVE_BADGE_STEP = "GIVE_BADGE_STEP";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
