export const GIVE_BADGE_SELECT_STUDENT = "GIVE_BADGE_SELECT_STUDENT";
export const GIVE_BADGE_SELECT_BADGE = "GIVE_BADGE_SELECT_BADGE";
export const GIVE_BADGE_CONFIRM_BADGE = "GIVE_BADGE_CONFIRM_BADGE";
export const GIVE_BADGE_SUCCESS = "GIVE_BADGE_SUCCESS";
export const GIVE_BADGE_STEP = "GIVE_BADGE_STEP";
export const CREATE_ACTIVITY_STEP = "CREATE_ACTIVITY_STEP";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const UPDATE_VERIFY_HASH = "UPDATE_VERIFY_HASH";
