export const SET_EVENTS = "SET_EVENTS";
export const SET_EVENT = "SET_EVENT";
export const UPDATE_SELECT_STUDENT = "UPDATE_SELECT_STUDENT";
export const UPDATE_GIVE_BADGE_STEP = "UPDATE_GIVE_BADGE_STEP";
