version: '3'
services:
  sitcom-api:
    container_name: sitcom-api
    build: .
    ports: 
      - '3000:3000'
    restart: on-failure
    volumes:
      - api:/usr/src/app/api
      - app:/usr/src/app/app
      - cmd:/usr/src/app/cmd
      - db:/usr/src/app/db
      - model:/usr/src/app/model
      - proto:/usr/src/app/proto
    depends_on:
      - sitcom-postgres          
    networks:
      - sitcom

  sitcom-postgres:
    image: postgres:latest
    container_name: sitcom-postgres
    environment:
      - POSTGRES_USER=sitcomadmin
      - POSTGRES_PASSWORD=thisispassword
      - POSTGRES_DB=sitcomdb
      - DATABASE_HOST=sitcom-postgres
    ports:
      - '5432:5432'
    volumes:
      #- database_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sitcom
    
  sitcom-web:
          # image: abiosoft/caddy:latest
    build:
      context: .
      dockerfile: "./frontend/local-dockerfile"
    ports:
      - "80:80"
    restart: always

volumes:
  api:
  app:
  cmd:
  db:
  model:
  proto:
  database_postgres:                  

networks:
  sitcom:
    driver: bridge

  # sitcom-web:
  #         # image: abiosoft/caddy:latest
  #   build:
  #     context: .
  #     dockerfile: "./frontend/Dockerfile"
  #   ports:
  #     - "80:80"
  #   restart: always

  # nginx:
  #   build: "./frontend"
  #   image: shakyshane/nginx-cors-plus
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "8080:8080"
  #   environment:
  #     -  TARGET=https://sitcompetence.ilab.sit.kmutt.ac.th
  #   depends_on:
  #     - "goservice"

