version: "3.3"
services:
  goservice:
    build: "."
    ports:
            - "3000:3000"
  nginx:
    build: "./nginx"
    image: shakyshane/nginx-cors-plus
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      -  TARGET=https://sitcompetence.ilab.sit.kmutt.ac.th
    depends_on:
      - "goservice"

