version: "3.3"
services:
  goservice:
    build: "."
    ports:
            - "3000:3000"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "goservice"

