version: '3.7'
services:
  sitcom-api:
    container_name: sitcom-api
    build: .
    ports: 
      - '3000:3000'
    restart: on-failure
    volumes:
      - api:/usr/src/app/api
      - app:/usr/src/app/app
      - cmd:/usr/src/app/cmd
      - db:/usr/src/app/db
      - model:/usr/src/app/model
      - proto:/usr/src/app/proto
    depends_on:
      - sitcom-postgres
    network_mode: host        
    #networks:
    #  - sitcom

  sitcom-postgres:
    image: postgres:latest
    container_name: sitcom-postgres
    environment:
      - POSTGRES_USER=sitcomadmin
      - POSTGRES_PASSWORD=thisispassword
      - POSTGRES_DB=sitcomdb
      - DATABASE_HOST=sitcom-postgres
    ports:
      - '5432:5432'
    volumes:
      #- database_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host
        #networks:
        #- sitcom
    
  sitcom-web:
    container_name: sitcom-web
    build:
      context: .
      dockerfile: "./frontend/Dockerfile"
    ports:
      - "80:80"
    restart: always
    network_mode: host
    depends_on:
      - sitcom-api
        #networks:
        #- sitcom

volumes:
  api:
  app:
  cmd:
  db:
  model:
  proto:
  database_postgres:                  

  #networks:
    #  sitcom:
      #    driver: bridge
