version: "3.3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sitcomadmin
      POSTGRES_PASSWORD: thisispassword
      POSTGRES_DB: sitcomdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  goservice:
    build: "."
    ports: 
      - "3000:3000"
    depends_on:
      - postgres

  sitcomweb:
    build:
      context: .
      dockerfile: "./frontend/Dockerfile-caddy"
    ports:
      - "80:80"
    restart: always
