version: '2.2'
services:
    server:
            image: golang:1.13-alpine
            volumes:
                    - .:/go/src/github.com/saguywalker/sitcompetence
            working_dir: /go/src/github.com/saguywalker/sitcompetence
            build:
                    context: ./
            ports:
                    -  3000
            container_name: go-server
