version: '3'
services:
  goservice:
    container_name: full_app
    build: .
    ports: 
      - 3000:3000 
    restart: on-failure
    depends_on:
      - fullstack-postgres          
    networks:
      - fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=sitcomadmin
      - POSTGRES_PASSWORD=thisispassword
      - POSTGRES_DB=sitcomdb
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  webservice:
    build: 
      context: .
      dockerfile: "./frontend/local-dockerfile"
    container_name: vue_web
    depends_on:
      - fullstack-postgres
      - goservice
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/:/app"
    command: /bin/sh -c "yarn serve"
    networks:
      - fullstack
    restart: unless-stopped

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
