openapi: 3.0.0
info:
  description: api between frontend and backend
  version: 1.0.0
  title: SIT-Competence API
servers:
  - url: http://localhost:3000/api
tags:
  - name: give-badge
x-tagGroups:
  - name: Admin
    tags:
      - give-badge
  - name: Blockchain
    tags:
      - debug
paths:
  /giveBadge:
    post:
      tags:
        - give-badge
      summary: Update Student data in Blockchain
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                selectedData:
                  type: array
                  properties:
                    id:
                      type: string
                    competence:
                      type: string
      responses:
        200:
          description: OK
          content:
            application:/json:
              schema:
                type: object
                properties:
                  block:
                    type: string
                    exmaple: hash `#fsdfsdfSE4w3rw`