// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tendermint.proto

package tendermint

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GiveBadge struct {
	StudentID            string   `protobuf:"bytes,1,opt,name=studentID,proto3" json:"studentID,omitempty"`
	CompetenceID         uint32   `protobuf:"varint,2,opt,name=competenceID,proto3" json:"competenceID,omitempty"`
	Semester             uint32   `protobuf:"varint,3,opt,name=semester,proto3" json:"semester,omitempty"`
	Giver                string   `protobuf:"bytes,4,opt,name=giver,proto3" json:"giver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GiveBadge) Reset()         { *m = GiveBadge{} }
func (m *GiveBadge) String() string { return proto.CompactTextString(m) }
func (*GiveBadge) ProtoMessage()    {}
func (*GiveBadge) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{0}
}

func (m *GiveBadge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiveBadge.Unmarshal(m, b)
}
func (m *GiveBadge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiveBadge.Marshal(b, m, deterministic)
}
func (m *GiveBadge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiveBadge.Merge(m, src)
}
func (m *GiveBadge) XXX_Size() int {
	return xxx_messageInfo_GiveBadge.Size(m)
}
func (m *GiveBadge) XXX_DiscardUnknown() {
	xxx_messageInfo_GiveBadge.DiscardUnknown(m)
}

var xxx_messageInfo_GiveBadge proto.InternalMessageInfo

func (m *GiveBadge) GetStudentID() string {
	if m != nil {
		return m.StudentID
	}
	return ""
}

func (m *GiveBadge) GetCompetenceID() uint32 {
	if m != nil {
		return m.CompetenceID
	}
	return 0
}

func (m *GiveBadge) GetSemester() uint32 {
	if m != nil {
		return m.Semester
	}
	return 0
}

func (m *GiveBadge) GetGiver() string {
	if m != nil {
		return m.Giver
	}
	return ""
}

type ApproveActivity struct {
	StudentID            string   `protobuf:"bytes,1,opt,name=studentID,proto3" json:"studentID,omitempty"`
	ActivityID           uint32   `protobuf:"varint,2,opt,name=activityID,proto3" json:"activityID,omitempty"`
	Semester             uint32   `protobuf:"varint,3,opt,name=semester,proto3" json:"semester,omitempty"`
	Approver             string   `protobuf:"bytes,4,opt,name=approver,proto3" json:"approver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveActivity) Reset()         { *m = ApproveActivity{} }
func (m *ApproveActivity) String() string { return proto.CompactTextString(m) }
func (*ApproveActivity) ProtoMessage()    {}
func (*ApproveActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{1}
}

func (m *ApproveActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveActivity.Unmarshal(m, b)
}
func (m *ApproveActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveActivity.Marshal(b, m, deterministic)
}
func (m *ApproveActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveActivity.Merge(m, src)
}
func (m *ApproveActivity) XXX_Size() int {
	return xxx_messageInfo_ApproveActivity.Size(m)
}
func (m *ApproveActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveActivity.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveActivity proto.InternalMessageInfo

func (m *ApproveActivity) GetStudentID() string {
	if m != nil {
		return m.StudentID
	}
	return ""
}

func (m *ApproveActivity) GetActivityID() uint32 {
	if m != nil {
		return m.ActivityID
	}
	return 0
}

func (m *ApproveActivity) GetSemester() uint32 {
	if m != nil {
		return m.Semester
	}
	return 0
}

func (m *ApproveActivity) GetApprover() string {
	if m != nil {
		return m.Approver
	}
	return ""
}

func init() {
	proto.RegisterType((*GiveBadge)(nil), "GiveBadge")
	proto.RegisterType((*ApproveActivity)(nil), "ApproveActivity")
}

func init() { proto.RegisterFile("tendermint.proto", fileDescriptor_04f926c8da23c367) }

var fileDescriptor_04f926c8da23c367 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe7, 0xe2,
	0x74, 0xcf, 0x2c, 0x4b, 0x75, 0x4a, 0x4c, 0x49, 0x4f, 0x15, 0x92, 0xe1, 0xe2, 0x2c, 0x2e, 0x29,
	0x4d, 0x49, 0xcd, 0x2b, 0xf1, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08,
	0x29, 0x71, 0xf1, 0x24, 0xe7, 0xe7, 0x16, 0xa4, 0x96, 0xa4, 0xe6, 0x25, 0xa7, 0x7a, 0xba, 0x48,
	0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0xa1, 0x88, 0x09, 0x49, 0x71, 0x71, 0x14, 0xa7, 0xe6, 0xa6,
	0x16, 0x97, 0xa4, 0x16, 0x49, 0x30, 0x83, 0xe5, 0xe1, 0x7c, 0x21, 0x11, 0x2e, 0xd6, 0xf4, 0xcc,
	0xb2, 0xd4, 0x22, 0x09, 0x16, 0xb0, 0xc9, 0x10, 0x8e, 0x52, 0x3b, 0x23, 0x17, 0xbf, 0x63, 0x41,
	0x41, 0x51, 0x7e, 0x59, 0xaa, 0x63, 0x72, 0x49, 0x66, 0x59, 0x66, 0x49, 0x25, 0x01, 0x77, 0xc8,
	0x71, 0x71, 0x25, 0x42, 0x55, 0xc2, 0x5d, 0x81, 0x24, 0x82, 0xd7, 0x0d, 0x52, 0x5c, 0x1c, 0x89,
	0x10, 0xcb, 0x60, 0xce, 0x80, 0xf3, 0x93, 0xd8, 0xc0, 0x21, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0x13, 0x7e, 0x2f, 0x25, 0x01, 0x00, 0x00,
}
