// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectedBadge struct {
	StudentID            string   `protobuf:"bytes,1,opt,name=studentID,proto3" json:"studentID,omitempty"`
	CompetenceID         uint32   `protobuf:"varint,2,opt,name=competenceID,proto3" json:"competenceID,omitempty"`
	Semester             uint32   `protobuf:"varint,3,opt,name=semester,proto3" json:"semester,omitempty"`
	Giver                []byte   `protobuf:"bytes,4,opt,name=giver,proto3" json:"giver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectedBadge) Reset()         { *m = CollectedBadge{} }
func (m *CollectedBadge) String() string { return proto.CompactTextString(m) }
func (*CollectedBadge) ProtoMessage()    {}
func (*CollectedBadge) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *CollectedBadge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectedBadge.Unmarshal(m, b)
}
func (m *CollectedBadge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectedBadge.Marshal(b, m, deterministic)
}
func (m *CollectedBadge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectedBadge.Merge(m, src)
}
func (m *CollectedBadge) XXX_Size() int {
	return xxx_messageInfo_CollectedBadge.Size(m)
}
func (m *CollectedBadge) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectedBadge.DiscardUnknown(m)
}

var xxx_messageInfo_CollectedBadge proto.InternalMessageInfo

func (m *CollectedBadge) GetStudentID() string {
	if m != nil {
		return m.StudentID
	}
	return ""
}

func (m *CollectedBadge) GetCompetenceID() uint32 {
	if m != nil {
		return m.CompetenceID
	}
	return 0
}

func (m *CollectedBadge) GetSemester() uint32 {
	if m != nil {
		return m.Semester
	}
	return 0
}

func (m *CollectedBadge) GetGiver() []byte {
	if m != nil {
		return m.Giver
	}
	return nil
}

func init() {
	proto.RegisterType((*CollectedBadge)(nil), "CollectedBadge")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x6a, 0x61, 0xe4, 0xe2, 0x73, 0xce, 0xcf, 0xc9, 0x49,
	0x4d, 0x2e, 0x49, 0x4d, 0x71, 0x4a, 0x4c, 0x49, 0x4f, 0x15, 0x92, 0xe1, 0xe2, 0x2c, 0x2e, 0x29,
	0x4d, 0x49, 0xcd, 0x2b, 0xf1, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08,
	0x29, 0x71, 0xf1, 0x24, 0xe7, 0xe7, 0x16, 0xa4, 0x96, 0xa4, 0xe6, 0x25, 0xa7, 0x7a, 0xba, 0x48,
	0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0xa1, 0x88, 0x09, 0x49, 0x71, 0x71, 0x14, 0xa7, 0xe6, 0xa6,
	0x16, 0x97, 0xa4, 0x16, 0x49, 0x30, 0x83, 0xe5, 0xe1, 0x7c, 0x21, 0x11, 0x2e, 0xd6, 0xf4, 0xcc,
	0xb2, 0xd4, 0x22, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x08, 0x27, 0x89, 0x0d, 0xec, 0x1a,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x6c, 0xbc, 0x6e, 0x9b, 0x00, 0x00, 0x00,
}
